[build]
builder = "nixpacks"
buildCommand = "npm run build"

[build.env]
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"
NEXT_PUBLIC_GOOGLE_MAP_ID = "$NEXT_PUBLIC_GOOGLE_MAP_ID"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
